config/routes.rb
#Resources provide REST-ful routes to Rails resources.
#REST Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete) to CRUD actions.

Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  #resources :articles 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# class Article inherits from application_record.rb
# Here we add constraints for article: title and desc must be present
# Title/desc length is set

class Article < ApplicationRecord
    validates :title, presence: true, length: { minimum: 6, maximum: 100 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [ :show, :edit, :update, :destroy]
    def show
    end    
    def index
        @articles5 = Article.all
    end
    def new
        @article = Article.new
    end
    def edit
    end
    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article
        else
            render "new"
            #render :new, status: :unprocessable_entity
        end
    end
    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            redirect_to @article
        else
            #render "edit"
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    private
    def set_article
        @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController #Pagescontroller inherits from Appcontroller
    def home
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h3>The following error prevented article save:</h3>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>
<%= form_with(model: @article, data: { turbo: false }, local: true) do |f| %>
    <p>
        <%= f.label :title %></br>
        <%= f.text_field :title %>
    </p>
    <p>
        <%= f.label :description %></br>
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Cool Article</h1>
<%= render "form" %>
<%= link_to "Cancel edit and return to articles listing", articles_path %>

app/views/articles/index.html.erb
<h1>All Articles Hub</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
        <% @articles5.each do |articlename| %>
            <tr>
                <td><%= articlename.title %></td>
                <td><%= articlename.description %></td>
                <td><%= link_to "Show", article_path(articlename) %></td>
                <td><%= link_to "Edit", edit_article_path(articlename) %></td>
                <td><%= link_to "Delete", article_path(articlename), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<p>
    <%= link_to "Create new article", new_article_path %>
</p>
<p>
<%= link_to "HomePage", root_path %> |
<%= link_to "About", about_path %> 
</p>

app/views/articles/new.html.erb
<h1>Create Cool Article</h1>
<%= render "form" %>
<%= link_to "Return to articles listing", articles_path %> | 
<%= link_to "HomePage", root_path %>

app/views/articles/show.html.erb
<h1>Very Special Article</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>
<p><strong>Time created: </strong><%= @article.created_at %></p>

<p>
<%= link_to "Edit", edit_article_path(@article) %> |
<%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %> |
<%= link_to "Return to articles listing", articles_path %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
    <%= msg %>
  <% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
    <a class="navbar-brand" id="logo" href="#">Rails Bar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Create</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Select
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Articles</a></li>
                <li><a class="dropdown-item" href="#">About action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Awarded</a></li>
              </ul>
            </li>

          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsUdemyDir</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    </head>

  <body>
    <%= render "layouts/navbar" %>

    <div class="container">
      <%= render "layouts/messages" %>
    </div>    
      <%= yield %>


  </body>
</html>

app/views/pages/about.html.erb
<h1>This is About page!</h1>

<p> Here you can tell me about yourself, like do you like electricity and stuff?</p>

<p>
<%= link_to "Articles listing", articles_path %> | 
<%= link_to "HomePage", root_path %>
</p>

app/views/pages/home.html.erb
  <div class="container" id="home-container">     
    <div class="jumbotron jumbotron-fluid text-center text-black">
      <h1 class="display-4">Rails on Udemy</h1>
      <p class="lead">This is a Rails on Udemy like no other. It might be once in a lifetime opportunity. Dont miss it, enjoy FOMO and follow us for more useful advices.</p>
      <button type="button" id="button-margin" class="btn btn-success">Jump in!</button>
    </div>
  </div>

  <div class="container" id="text-container">
    <p>
      And now, <b>showtime!</b> We proudly present to you:</br>
      <%= link_to "Link to the Articles listing!", articles_path %> | 
      <%= link_to "About page!", about_path %>
    </p>
  </div>
  

<footer class="footer mt-auto py-3 text-white">
<span class="text-muted">Copyleft by Rails on Udemy 2023</span>
</footer>